<!DOCTYPE paises [
<!ELEMENT paises (pais*)>
<!ELEMENT pais (nombre, unionEuropea?)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT unionEuropea EMPTY>
]>
<paises>
    <pais>
        <nombre>Espa√±a</nombre>
        <unionEuropea/>
    </pais>
    <pais>
        <nombre>Noruega</nombre>
    </pais>
    <pais>
        <nombre>Austria</nombre>
    </pais>
</paises>